import type { Metadata } from "next";
import { Aleo } from "next/font/google";
import { Providers } from './providers'
import "./globals.css";

const inter = Aleo({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Combat Maps",
  description: "Generated by create next app",
  icons: {
    icon: "/icon_cf.png"
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}><Providers>{children}</Providers></body>
    </html>
  );
}
